Small fixes in the Readme
ARMmbed/mbed-os-example-bootloader pull request #5
Opened 2017-03-23 09:32 UTC by 0xc0170

@ashok-rao Please review

2017-03-23 11:33 UTC, ashok-rao approved these changes
LGTM 👍.. Apart from the mention of the blinky_application.bin in main.cpp in the repo, other docs changes are fine. Will @c1728p9 be addressing the point in main.cpp?

2017-03-23 11:47 UTC, 0xc0170 commented
> Apart from the mention of the blinky_application.bin in main.cpp in the repo, other docs changes are fine. Will @c1728p9 be addressing the point in main.cpp?

This define: https://github.com/ARMmbed/mbed-os-example-bootloader/blob/master/main.cpp#L5 ?

2017-03-23 11:57 UTC, ashok-rao commented
Yes @0xc0170 , that one.. SD card for just building the bootloader binary (as per the README) seems a bit out-of-place..also we might want to make this as starting point for all examples..even filesystems ones.. so better to keep it generic than hard code a particular binary / example to it..

@c1728p9 @screamerbg , @sg- .. what do you think?

2017-03-23 12:08 UTC, 0xc0170 commented
> Yes @0xc0170 , that one.. SD card for just building the bootloader binary (as per the README) seems a bit out-of-place..also we might want to make this as starting point for all examples..even filesystems ones.. so better to keep it generic than hard code a particular binary / example to it..

New update - removed not needed parts (CI, SD card), replace nucleo target by a generic target name

2017-03-23 12:17 UTC, ashok-rao commented
LGTM .. we just need @c1728p9 to confirm about https://github.com/ARMmbed/mbed-os-example-bootloader/blob/master/main.cpp#L5 .. Rest all good to go!

2017-03-23 15:06 UTC, sg- commented
I've always liked the idea of offset built images having the offset in the name (see DAPLink). I think we should implement that here / in the tools too

2017-03-23 15:36 UTC, 0xc0170 commented
> I've always liked the idea of offset built images having the offset in the name (see DAPLink). I think we should implement that here / in the tools too rather than using the word bootloader everywhere

sounds good to me to have it in the name. @c1728p9 What do you think? If we make it in the tools, I can update the docs

2017-03-23 15:38 UTC, ashok-rao commented
That would avoid a LOT of confusions.. +1 to have the distinctions in the file names itself.

2017-03-23 16:24 UTC, c1728p9 commented on README.md
> -* SD card.
The bootloader in the example is setup specifically to use an SD card on the CI Test shield. Without this none of the bootloader functionality can be used.

2017-03-23 16:28 UTC, c1728p9 commented
I don't have strong feelings either way on having the starting address of an application/bootloader as part of the name. @theotherjimmy what are your thoughts on this?

2017-03-23 16:43 UTC, 0xc0170 commented on README.md
> -* SD card.
Will fix

2017-03-23 17:42 UTC, ashok-rao commented on README.md
> -* SD card.
@c1728p9 , as per the README, this example only "builds" the bootloader binary.. there is no mention of updating it or any other BL functionality. Should we modify the README then?

2017-03-23 17:45 UTC, ashok-rao commented
>I don't have strong feelings either way on having the starting address of an application/bootloader as part of the name. @theotherjimmy what are your thoughts on this?

I think this refers to using the "_application" or the "_bl" in the file names? And not the actual offset addresses..I maybe wrong..

2017-03-23 18:21 UTC, ashok-rao commented on README.md
>  When the build succeeds, you have created a bootloader for your target. The next step is to build an application you can combine with your bootloader to create a loadable image. You can find a blinky
"When it builds, you have created a bootloader for your target. The next step is to build an application .... " I think this statement is ambiguous. So, this application "only" builds the BL binary. I have to go to another application that uses this bootloader. So, why do we need to mention the SD card or test the "update" functionality of the bootloader here with an  SD card??

2017-03-23 18:22 UTC, ashok-rao requested changes
Some lines in the "Next steps" section are confusing. Please review.

How about finding some other means of testing the BL -> like flash the new bootloader, make sure the DAPLink interface can still be upgraded/downgraded on the target or atleast make sure the DAPLink can be written to the device again & the target is still enumerated as mbed ? etc etc..

2017-03-23 19:15 UTC, sg- commented
The proposal would be the following:
- application without a bootloader, <program name>
- application with constrain, <program name>-<?? or maybe blank ??>
- application with bootloader.bin, <program name>-<loadaddress 0x123455>

2017-03-24 09:53 UTC, 0xc0170 commented on README.md
> -* SD card.
I'll fix it

2017-03-24 09:53 UTC, 0xc0170 commented on README.md
>  When the build succeeds, you have created a bootloader for your target. The next step is to build an application you can combine with your bootloader to create a loadable image. You can find a blinky
I'll rewrite this section, noticed the same

2017-03-24 10:04 UTC, 0xc0170 commented
@ashok-rao I added SD card explanation, please review

2017-03-27 06:55 UTC, 0xc0170 commented
@ashok-rao Please review, or make edits here. I would like to proceed with this Readme update.

2017-03-27 08:29 UTC, ashok-rao commented
@0xc0170 .. Ok, let's proceed with this for now. I'll make edits as I find suitable and raise other PR's. Thanks!

2017-03-27 08:29 UTC, ashok-rao approved these changes

2017-03-27 08:30 UTC, ashok-rao commented
I have approved now. Please go ahead to merge :-)

2017-03-27 11:27 UTC, merged